### ISSUE TITLE
Concurrent usages?

### ISSUE THREAD

**Issue by martijnburgers** [Api2Pdf/api2pdf.dotnet#6]
How does this library needs to be used in a concurrent way? Because of the http client being static I get all kind of errors.

**Comment by martijnburgers** [comment]
Made a quick fix by coping code and use a http client factory and add api key before passing it to api2pdf class.

Here you can find more info how to use http clients, https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0

**Comment by apexdodge** [comment]
Good to know for those need this functionality.

**Comment by martijnburgers** [comment]
That's almost everyone (doing web or messaging applications). So it would be good to include this in the package.

**Comment by smoelker** [comment]
This issue still persists because no solution was provided. Storing manually constructed HttpContext instances in a static variable violates Microsoft's [guidelines](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines). It can lead to various problem like stale DNS.

The solution is to not construct a long lived HttpContext instance but to take a HttpContext as a dependency.

I'm happy to create a PR to solve this.
